### ISSUE TITLE
Standardise Difficulties, Tags, Topics of Questions

### ISSUE THREAD

**Issue by zhangj1an** [AY1920S1-CS2103T-F14-1/main#49]
Difficulties : Enum. `Easy`, `Medium`, `Hard` . </br>
Topics: Enum.  `Array`, `Stack`, `Queue`, `Linked List`, `Tree`, `Graph`, `Hash Table`, etc.  </br>
Tags: Use ArrayList to store available tags. Example: `Google2019`, `CS2040AY1819S1`.

**Comment by limhawjia** [comment]
Closing this issue, was resolved in my commit
